# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

#Pipelines > Stages > Jobs > Tasks(Steps)

jobs:
- job: Job1
  steps:
  - script: echo Job 2!
    displayName: 'Run Job1'

- job: Job2
  steps:
  - script: echo Job 1!
    displayName: 'Run Job12'